SWE2_TP2_4/Models/BL.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SWE2_TP2_4.Models
{
    public class BL
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public string Consignee { get; set; }

        public string Navio { get; set; }
        public int ContainerId { get; set; }
    }
}

SWE2_TP2_4/Models/Container.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SWE2_TP2_4.Models
{
    public class Container
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public string Tipo { get; set; }
        public string Tamanho { get; set; }
    }
}

SWE2_TP2_4/Controllers/BLController.cs
using SWE2_TP2_4.DAO;
using SWE2_TP2_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace SWE2_TP2_4.Controllers
{
    public class BLController : Controller
    {
        public ActionResult BLIndex()
        {
            BLDAO dao = new BLDAO();

            IList<BL> produtos = dao.Lista();
            ViewBag.BL = produtos;
            return View();

        }

        [HttpPost]
        public ActionResult Adiciona(BL categoria)
        {
            MessageBox.Show("Controller");
            MessageBox.Show(categoria.Consignee);
            BLDAO dao = new BLDAO();
            dao.Adiciona(categoria);
            return RedirectToAction("BLIndex");
        }
        public ActionResult BLForm()
        {

            return View();
        }
        public ActionResult BLPesquisa()
        {
            return View();
        }

        public ActionResult BLPesquisa2()
        {
            return View();
        }
        public ActionResult Pesquisa(int Id)
        {
            BLDAO dao = new BLDAO();
            ViewBag.Busca = dao.BuscaPorId(Id);
            MessageBox.Show(ViewBag.Busca.Numero.ToString());
            MessageBox.Show(ViewBag.Busca.Consignee);
            MessageBox.Show(ViewBag.Busca.Navio);
            return RedirectToAction("BLPesquisa2");

        }
    }
}

SWE2_TP2_4/Controllers/ContainerController.cs
using SWE2_TP2_4.DAO;
using SWE2_TP2_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace SWE2_TP2_4.Controllers
{
    public class ContainerController : Controller
    {
        public ActionResult ContainerIndex()
        {
            ContainerDAO dao = new ContainerDAO();

            IList<Container> produtos = dao.Lista();
            ViewBag.Container = produtos;

            return View();
        }

        [HttpPost]
        public ActionResult Adiciona(Container categoria)
        {
            ContainerDAO dao = new ContainerDAO();
            dao.Adiciona(categoria);
            return RedirectToAction("ContainerIndex");
        }

        public ActionResult ContainerForm()
        {
            return View();
        }
        public ActionResult ContainerPesquisa()
        {
            return View();
        }

        public ActionResult ContainerPesquisa2()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Pesquisa(int Id)
        {
           // Container cont = new Container();
            ContainerDAO dao = new ContainerDAO();
            //Container cont = dao.BuscaPorId(Id);
            ViewBag.Busca = dao.BuscaPorId(Id);
            //MessageBox.Show(cont.Numero.ToString());
            //MessageBox.Show(cont.Numero.ToString());
            MessageBox.Show(ViewBag.Busca.Tipo);
            MessageBox.Show(ViewBag.Busca.Tipo);
            //MessageBox.Show(ViewBag.Busca.Tamanho);
            return RedirectToAction("ContainerPesquisa2", ViewBag.Busca);

        }
    }
}

SWE2_TP2_4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SWE2_TP2_4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SWE2_TP2_4/Views/BL/BLForm.cshtml
@{
    Layout = null;
}
<html>
<head>
</head>
<body>
    <form action="/BL/Adiciona" method="post">
        <ul>
            <li>
                <label for="Numero">Numero:</label>
                <input name="categoria.Numero" id="Numero" />
            </li>
            <li>

                <label for="Consignee">Consignee:</label>
                <input name="categoria.Consignee" id="Consignee" />
            </li>
            <li>

                <label for="Navio">Navio:</label>
                <input name="categoria.Navio" id="Navio" />
            </li>
            <li>

                <label for="ContainerId">Container:</label>
                <input name="categoria.ContainerId" id="ContainerId" />
            </li>
            <li>

                <input type="submit" value="Cadastrar" />
            </li>
           
        </ul>
    </form>
</body>
</html>

SWE2_TP2_4/Views/BL/BLIndex.cshtml
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>
            @*<li>@Html.ActionLink("Adicionar BL", "BLForm", "BL")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar BL", "BLForm", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Pesquisa BL", "BLPesquisa", "BL")</li>

        </ul>
            <h3 class="muted-text">Lista de BL´s</h3>

    </div>
    <table class="table table-hover">

        <thead>
            <tr>
                <th>Numero </th>
                <th>    |   </th>
                <th>  Consignee  </th>
                <th>    |   </th>
                <th>  Navio</th>
                <th>    |   </th>
                <th>  Container  </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var produto in ViewBag.BL)
            {

            <tr>

                <td>@produto.Numero</td>
                <th>    |   </th>
                <td>@produto.Consignee</td>
                <th>    |   </th>
                <td>@produto.Navio</td>
                <th>    |   </th>
                <td>@produto.ContainerId</td>

            </tr>
            }

        </tbody>
    </table>
</body>

SWE2_TP2_4/Views/BL/BLPesquisa.cshtml
<html>
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("BL", "BLIndex", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>
            @*<li>@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar BL", "BLForm", "BL")</li>
            </ul>

        <h3 class="muted-text">Lista de BL</h3>

    </div>
    <form action="/BL/Pesquisa" method="post">
        <ul>
            <li>
                <label for="Id">Id:</label>
                <input name="Id" id="Id" />
            </li>
            <li>
                <input type="submit" value="Buscar" />
            </li>
        </ul>
    </form>
</body>
</html>

SWE2_TP2_4/Views/BL/BLPesquisa2.cshtml
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("BL", "BLIndex", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>
            @*<li>@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar BL", "BLForm", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Pesquisa BL", "BLPesquisa", "BL")</li>
        </ul>

        <h3 class="muted-text">Visualização de BL</h3>

    </div>
    <table class="table table-hover">

        <thead>
            <tr>
                <th>Numero  </th>
                <th>    |   </th>
                <th>  Tipo  </th>
                <th>    |   </th>
                <th>  Tamanho</th>
            </tr>
        </thead>
        <tbody>

            @*@foreach (var produto in ViewBag.Busca)
                {
                    <tr>
                        <td>@produto.Numero.ToString()</td>
                        <th>    |   </th>
                        <td>@produto.Tipo</td>
                        <th>    |   </th>
                        <td>@produto.Tamanho</td>
                    </tr>
                }*@

            @*<tr>
                    <td>@ViewBag.Busca.Numero.ToString()</td>
                    <th>    |   </th>
                    <td>@ViewBag.Busca.Tipo</td>
                    <th>    |   </th>
                    <td>@ViewBag.Busca.Tamanho</td>
                </tr>*@

        </tbody>
    </table>
</body>

SWE2_TP2_4/Views/Container/ContainerForm.cshtml
<html>
<head>
</head>
<body>
    <form action="/Container/Adiciona" method="post">
        <ul>
            <li>
                <label for="Numero">Numero:</label>
                <input name="categoria.Numero" id="Numero" />
            </li>
            <li>

                <label for="Tipo">Tipo:</label>
                <input name="categoria.Tipo" id="Tipo" />
            </li>
            <li>

                <label for="Tamanho">Tamanho:</label>
                <input name="categoria.Tamanho" id="Tamanho" />
            </li>
            <li>

                <input type="submit" value="Cadastrar" />
            </li>

        </ul>
    </form>
</body>
</html>

SWE2_TP2_4/Views/Container/ContainerIndex.cshtml
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("BL", "BLIndex", "BL")</li>
            @*<li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>*@
            @*<li>@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Pesquisa Container", "ContainerPesquisa", "Container")</li>
        </ul>

            <h3 class="muted-text">Lista de Containers</h3>

    </div>
    <table class="table table-hover">

        <thead>
            <tr>
                <th>Numero  </th>
                <th>    |   </th>
                <th>  Tipo  </th>
                <th>    |   </th>
                <th>  Tamanho</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var produto in ViewBag.Container)
            {
            <tr>
                <td>@produto.Numero</td>
                <th>    |   </th>
                <td>@produto.Tipo</td>
                <th>    |   </th>
                <td>@produto.Tamanho</td>
            </tr>
            }

        </tbody>
    </table>
</body>

SWE2_TP2_4/Views/Container/ContainerPesquisa.cshtml
<html>
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("BL", "BLIndex", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>
            @*<li>@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>
            @*<li style="display:inline">     |     </li>*@
            @*<li style="display:inline">@Html.ActionLink("Pesquisa Container", "ContainerPesquisa", "Container")</li>*@
        </ul>

        <h3 class="muted-text">Lista de Containers</h3>

    </div>
    <form action="/Container/Pesquisa" method="post">
        <ul>
            <li>
                <label for="Id">Id:</label>
                <input name="Id" id="Id" />
            </li>
            <li>
                <input type="submit" value="Buscar" />
            </li>
        </ul>
    </form>
</body>
</html>

SWE2_TP2_4/Views/Container/ContainerPesquisa2.cshtml
<html>
<body>
    <div class="header">

        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Home", "Index", "Home")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("BL", "BLIndex", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>
            @*<li>@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>*@
        </ul>
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("Adicionar Container", "ContainerForm", "Container")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Pesquisa Container", "ContainerPesquisa", "Container")</li>
        </ul>

        <h3 class="muted-text">Visualização de Container</h3>

    </div>
    <table class="table table-hover">

        <thead>
            <tr>
                <th>Numero  </th>
                <th>    |   </th>
                <th>  Tipo  </th>
                <th>    |   </th>
                <th>  Tamanho</th>
            </tr>
        </thead>
        <tbody>

            @*@foreach (var produto in ViewBag.Busca)
        {
            <tr>
                <td>@produto.Numero.ToString()</td>
                <th>    |   </th>
                <td>@produto.Tipo</td>
                <th>    |   </th>
                <td>@produto.Tamanho</td>
            </tr>
        }*@

            <!--<tr>-->
                @*<td>@ViewBag.Busca.Numero</td>*@
                <!--<th>    |   </th>
                <td>@ViewBag.Busca.Tipo</td>
                <th>    |   </th>
                <td>@ViewBag.Busca.Tamanho</td>
            </tr>-->
            @*<tr>
                <td>@cont.Numero</td>
                <th>    |   </th>
                <td>@cont.Tipo</td>
                <th>    |   </th>
                <td>cont.Tamanho</td>
            </tr>*@

        </tbody>
    </table>
</body>
</html>

SWE2_TP2_4/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Página Inicial</h1>
    @*<br />*@
    <h2 class="display-4">Seja Bem Vindo</h2>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>
<body>
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li style="display:inline">@Html.ActionLink("BL´s", "BLIndex", "BL")</li>
            <li style="display:inline">     |     </li>
            <li style="display:inline">@Html.ActionLink("Containers", "ContainerIndex", "Container")</li>

        </ul>
        @*<h3 class="muted-text">Caelum Estoque</h3>*@
    </div>
    @*<div>
            @RenderBody()
        </div>*@
</body>